name:          RCC Web Style Guide
description:   HTML/CSS standards and best practices
url:           http://rcc-uchicago.github.io/web-style-guide/
markdown:      rdiscount
permalink:     pretty
pygments:      true
